FROM node:22-alpine

# WORKDIR /app

# COPY package.json ./
# COPY vite.config.ts ./
# COPY tsconfig.json ./

# RUN npm install

# COPY . .

# EXPOSE 3000

# CMD ["npm", "start"]



WORKDIR /app

COPY package.json tsconfig.json vite.config.ts ./
RUN npm install

COPY ./src ./src
COPY index.html ./

EXPOSE 3000

CMD ["npm", "run", "dev"]

